name: GH Release, Publishing to Docker and Deployment to Heroku

on: [push, pull_request]

# on:
#   push:
#     tags:
#       - 'v*.*.*'


jobs:

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.9

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pytest pytest-cov requests
  #         if [ -f requirements-prod.txt ]; then pip install -r requirements-prod.txt; fi

  #     - name: Generate coverage report
  #       run: |
  #         pytest --cov=app --cov-report=xml

  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v1
  #       with:
  #         files: ./coverage.xml
  #         directory: ./coverage/reports/
  #         name: codecov-umbrella
  #         fail_ci_if_error: true
  #         path_to_write_report: ./coverage/codecov_report.txt
  #         verbose: true


  # build-dockerimage:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: build dockerimage
  #       run: |
  #         docker build -t gh-trending-api .



  # docker-publish:
  #   needs: [test, build-dockerimage]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Publish to Registry
  #     uses: elgohr/Publish-Docker-Github-Action@master
  #     with:
  #       name: niklastiede/github-trending-api
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}


  heroku-deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy on Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "gh-trending-api"
        heroku_email: "niklastiede2@gmail.com"
        # usedocker: true









  # release-and-deploy:
  #   # needs: [test, build-dockerimage]

  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  # #     # - name: Release
  # #     #   uses: softprops/action-gh-release@v1
  # #     #   env:
  # #     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Publish to Registry
  #       uses: elgohr/Publish-Docker-Github-Action@master
  #       with:
  #         name: niklastiede/github-trending-api
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Deploy on Heroku
  #     - uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: "gh-trending-api"
  #         heroku_email: "niklastiede2@gmail.com"
  #         usedocker: true
