name: GH Release and Deploy on Heroku


on: [push, pull_request]

# on:
#   push:
#     tags:
#       - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish to Registry
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: niklastiede/testing_workflows
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gh-trending-api"
          heroku_email: "niklastiede2@gmail.com"

